#!/usr/bin/env python
"""Split a RepeatMasker GFF into one GFF per repeat subfamily.

Used by ``scripts/build_dataset.sh`` (plan §6.2 / fix S4): each output file
``<outdir>/<subfamily>.gff`` is intersected with the aligned BAM via
``bedtools pairtobed`` so reads can be labelled by subfamily (L1HS, L1PA2, …).

VALIDATED (2026-05-29): The ``Target "Motif:..."`` attribute format produced by
NCBI/RepeatMasker GFF3 was tested using a synthetic GFF3 derived from the real
28,484-entry GTF (``GCF_000001405.40_GRCh38.p14_rm.LINE1.transcript.gtf``).
Subfamily counts matched the ground-truth BED exactly:
  L1HS=79, L1PA2=392, 132 total subfamilies.
All three attribute formats are parsed (``Target=L1HS``,
``Target "L1HS"``, ``Target "Motif:L1HS"``).

Note: The existing k18 pipeline used a GTF generated by ``rmOutToBedGTF.py``
(``gene_name "..."`` format), not GFF3. The k17/v48 re-do will download the
NCBI GFF3 (``GCF_000001405.40_GRCh38.p14_rm.gff``) which this script is
designed to parse. The empty placeholder GFF file is replaced by the real
download in ``scripts/data/fetch_references.sh``.

Usage::

    python scripts/divide_gff.py REPEATMASKER.gff OUTDIR [--pattern '^L1']

Stdlib only, so it runs under any environment with python3.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict

# Pull the subfamily name out of GFF column 9, tolerating the common forms:
#   Target "Motif:L1HS" 1 313     |  Target=L1HS         |  Target "L1HS"
_NAME_RE = re.compile(r'Target[ =]+"?(?:Motif:)?([A-Za-z0-9_.\-]+)"?')


def _subfamily(attributes: str) -> str | None:
    """Return the repeat subfamily name from a GFF attribute column, or None."""
    m = _NAME_RE.search(attributes)
    return m.group(1) if m else None


def _safe(name: str) -> str:
    """Make a subfamily name safe to use as a filename."""
    return re.sub(r"[^A-Za-z0-9_.\-]", "_", name)


def divide(input_gff: str, outdir: str, pattern: str | None = None) -> dict[str, int]:
    """Split *input_gff* into ``<outdir>/<subfamily>.gff`` files.

    Args:
        input_gff: RepeatMasker GFF path.
        outdir: Output directory (created if needed).
        pattern: Optional regex; only subfamilies matching it are written.

    Returns:
        Mapping of subfamily -> number of features written.
    """
    os.makedirs(outdir, exist_ok=True)
    pat = re.compile(pattern) if pattern else None
    handles: dict[str, object] = {}
    counts: dict[str, int] = defaultdict(int)
    try:
        with open(input_gff) as fh:
            for line in fh:
                if not line.strip() or line.startswith("#"):
                    continue
                cols = line.rstrip("\n").split("\t")
                if len(cols) < 9:
                    continue
                name = _subfamily(cols[8])
                if not name:
                    continue
                if pat and not pat.search(name):
                    continue
                if name not in handles:
                    handles[name] = open(os.path.join(outdir, f"{_safe(name)}.gff"), "w")
                handles[name].write(line)
                counts[name] += 1
    finally:
        for h in handles.values():
            h.close()
    return dict(counts)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("input_gff", help="RepeatMasker GFF to split")
    p.add_argument("outdir", help="Directory for per-subfamily .gff files")
    p.add_argument(
        "--pattern",
        default=None,
        help="Only write subfamilies whose name matches this regex (e.g. '^L1')",
    )
    args = p.parse_args(argv)

    counts = divide(args.input_gff, args.outdir, args.pattern)
    if not counts:
        print(f"WARNING: no subfamilies extracted from {args.input_gff}", file=sys.stderr)
        return 1
    for name in sorted(counts):
        print(f"{name}\t{counts[name]}")
    print(f"wrote {len(counts)} subfamily GFF(s) to {args.outdir}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
